#!/usr/bin/python3

import llxupgrader

url="https://raw.githubusercontent.com/juanma1980/llx-upgrade-release/master/files/meta-release"
meta=llxupgrader.downloadFile(url)
with open(meta,"r") as f:
	metadata=llxupgrader.processMetaRelease(f.readlines())

upgradeTo=llxupgrader.chkReleaseAvailable(metadata)
if len(upgradeTo)>0:
	print("Upgrade available: {}".format(upgradeTo["Name"].split(":")[1].strip()))
	upgrade=input("Upgrade? y/[n]: ")
	if upgrade!="y":
		print(i18n("ABORT"))
		sys.exit(2)
if llxupgrader.disclaimerAgree()==False:
	print(i18n("ABORT"))
	sys.exit(2)
print()
print(i18n("BEGIN"))
if llxupgrader.upgradeCurrentState():
	print(i18n.get("PENDING"))
	sys.exit(3)
print(i18n("DISABLE"))
print(i18n("DEFAULT"))
print("\n  **** {} **** \n".format(i18n("UNDO").upper()))
abort=input("[n]/ok: ")
if abort!="ok":
	print(i18n("ABORT"))
	sys.exit(2)
tools=llxupgrader.prepareFiles(upgradeTo)
llxupgrader.disableRepos()
print(i18n("EXTRACT"))
llxupgrader.enableUpgradeRepos(tools)
llxupgrader.launchLliurexUp()
llxupgrader.chkUpgradeResult()
sys.exit(0)
