#!/usr/bin/python3
# Copyright (c) 2023 LliureX Team
# This code is released under the GPL-3 terms
# https://www.gnu.org/licenses/gpl-3.0.en.html#license-text

import os,sys,subprocess,time
import llxupgrader
from PySide2.QtWidgets import QApplication, QLabel, QWidget, QPushButton,QGridLayout,QListWidget,QTextEdit, QCheckBox,QListWidgetItem,QSizePolicy,QProgressBar
from PySide2 import QtGui
from PySide2.QtCore import QSize,Qt,QThread,Signal,QObject

class thProgress(QThread): 
	end=Signal()
	disabled=Signal()
	downgraded=Signal()
	def __init__(self,parent=None):
		super (thProgress,self).__init__(parent)
		self.prg=QProgressBar()

	def run(self):
		val=0
		while val<100:
			val=self.prg.prg.value()
			self.prg.prg.setValue(val+1)
			time.sleep(1)

#class thRun
class thRun(QThread): 
	end=Signal()
	disabled=Signal()
	downgraded=Signal()
	def __init__(self,parent=None):
		super (thRun,self).__init__(parent)
		self.target=""
		self.upgradeTo=""

	def setTarget(self,target):
		self.target=target

	def run(self):
		if self.target=="disablerepos":
			llxupgrader.disableRepos()
			self.disabled.emit()
		if self.target=="doUpgrade":
			tools=llxupgrader.prepareFiles(self.upgradeTo)
			llxupgrader.enableUpgradeRepos(tools)
			llxupgrader.downloadPackages()
			llxupgrader.generateLocalRepo()
			llxupgrader.setLocalRepo()
			#llxupgrader.launchLliurexUp()
			self.end.emit()
		if self.target=="downgrade":
			llxupgrader.downgrade()
			self.downgraded.emit()
#class thRun

class QStepLine(QWidget):
	clicked=Signal()
	def __init__(self,parent=None):
		super (QStepLine,self).__init__(parent)
		lay=QGridLayout()
		self.lbl_info=QLabel()
		self.lbl_info.setWordWrap(True)
		self.btn_ok=QPushButton(llxupgrader.i18n("ACCEPT"))
		self.btn_ok.clicked.connect(self.emitOk)
		self.btn_ko=QPushButton(llxupgrader.i18n("CANCEL"))
		self.btn_ko.clicked.connect(self.cancel)
		lay.addWidget(self.lbl_info,0,0,1,2)
		lay.addWidget(self.btn_ok,1,0,1,1,Qt.AlignLeft)
		lay.addWidget(self.btn_ko,1,1,1,1,Qt.AlignRight)
		self.setLayout(lay)
		self.prg=QProgressBar()
		lay.addWidget(self.prg,0,0,1,2)
		self.prg.setVisible(False)
		return
	#def __init__

	def enableImg(self,image):
		self.prg.setVisible(True)
		self.prg.setFixedHeight(self.height())
		self.prg.setFixedWidth(self.width())
		self.setStyleSheet("QProgressBar {padding:0px;border:0px}\nQProgressBar::chunk {border-image:url('/usr/share/llx-upgrade-release/rsrc/bkg.png') 0 0 0 0 stretch}")
		self.prg.setValue(0)
		self.lbl_info.setVisible(False)

	def setText(self,msg):
		self.lbl_info.setText(msg)
	#def setText

	def emitOk(self):
		self.setDisabled(True)
		self.clicked.emit()
	#def emitOk

	def cancel(self):
		self.btn_ok.setDisabled(True)
	#def cancel
#class QStepLine

class upgraderGui(QWidget):
	def __init__(self,parent=None):
		super (upgraderGui,self).__init__(parent)
		self.upgradeTo=self.chkUpAvailable()
		self.th=thRun()
		self.thProgress=thProgress()
		self.th.upgradeTo=self.upgradeTo.copy()
		self.noreturn=0
	#def __init__

	def closeEvent(self,event):
		if self.noreturn==1:
			event.ignore()

	def _revertAll(self):
		llxupgrader.restoreRepos()
		item = QListWidgetItem(self.lst_Steps)
		lbl_info=QStepLine()
		lbl_info.btn_ko.setVisible(False)
		lbl_info.clicked.connect(self._launchUp)
		msg=[llxupgrader.i18n("ABORT"),llxupgrader.i18n("REVERT"),llxupgrader.i18n("RECOM")]
		lbl_info.setText("<br><br>".join(msg))
		self.lst_Steps.addItem(item)
		self.lst_Steps.setItemWidget(item,lbl_info)
		item.setSizeHint(QSize(lbl_info.lbl_info.width(), lbl_info.sizeHint().height()))
		self.lst_Steps.setCurrentItem(item)
		self.noreturn=0
	#def _revertAll

	def _launchUp(self):
		os.execv("/usr/sbin/lliurex-up",["-n"])
	#def self._launchUp

	def _endUpgradeFailed(self):
		item = QListWidgetItem(self.lst_Steps)
		lbl_info=QStepLine()
		lbl_info.btn_ko.setVisible(False)
		lbl_info.btn_ok.setVisible(False)
		lbl_info.setText("<p><pre>{}</pre></p><p><b>{}</b></p>".format(llxupgrader.i18n("PRAY"),llxupgrader.i18n("PRAY2")))
		self.lst_Steps.addItem(item)
		self.lst_Steps.setItemWidget(item,lbl_info)
		item.setSizeHint(QSize(lbl_info.lbl_info.width(), lbl_info.sizeHint().height()))
		self.lst_Steps.setCurrentItem(item)
		self.noreturn=0

	def _beginUpgradeFailed(self):
		self._revertAll()
		self.noreturn=1
		item=self.lst_Steps.currentItem()
		wdg=self.lst_Steps.itemWidget(item)
		wdg.btn_ok.setVisible(False)
		
		item = QListWidgetItem(self.lst_Steps)
		lbl_info=QStepLine()
		lbl_info.btn_ko.setVisible(False)
		lbl_info.btn_ok.setVisible(False)
		lbl_info.setText("<br>{}<br>".format(llxupgrader.i18n("DOWNGRADE")))
		self.lst_Steps.addItem(item)
		self.lst_Steps.setItemWidget(item,lbl_info)
		item.setSizeHint(QSize(lbl_info.lbl_info.width(), lbl_info.sizeHint().height()))
		self.lst_Steps.setCurrentItem(item)
		self.th.setTarget("downgrade")
		self.th.start()
		self.th.downgraded.connect(self._endUpgradeFailed)
	#def _beginUpgradeFailed

	def _launch(self):
		cmd=["systemctl","isolate","llx-upgrade"]
		subprocess.run(cmd)
		sys.exit(noreturn)
		
	def _endUpgrade(self):
		val=self.thProgress.prg.prg.value()
		while val<90:
			val+=0.1
			self.thProgress.prg.prg.setValue(val)
			time.sleep(0.01)
		time.sleep(1)
		item = QListWidgetItem(self.lst_Steps)
		lbl_info=QStepLine()
		lbl_info.btn_ok.clicked.connect(self._launch)
		self.upgradeTo=self.chkUpAvailable()
#		if len(self.upgradeTo)>0:
#			lbl_info.setText("{0}<br>{1}".format(llxupgrader.i18n("REBOOT2"),llxupgrader.i18n("REBOOT3")))
#			lbl_info.btn_ko.clicked.connect(self._beginUpgradeFailed)
#			lbl_info.btn_ok.setVisible(False)
#			lbl_info.btn_ko.setVisible(True)
#		else:
		lbl_info.setText("{0}<br>{1}".format(llxupgrader.i18n("REBOOT"),llxupgrader.i18n("END")))
		lbl_info.btn_ok.setVisible(True)
		self.noreturn=0
		self.lst_Steps.addItem(item)
		self.lst_Steps.setItemWidget(item,lbl_info)
		self.lst_Steps.setCurrentItem(item)
		item.setSizeHint(QSize(lbl_info.lbl_info.width(), lbl_info.sizeHint().height()))
	#def _endUpgrade

	def _doLastStepUpgrade(self):
		item = QListWidgetItem(self.lst_Steps)
		lbl_info=QStepLine()
		#lbl_info.setText(llxupgrader.i18n("SETTINGUP"))
		lbl_info.btn_ok.setVisible(False)
		lbl_info.btn_ko.setVisible(False)
		self.lst_Steps.addItem(item)
		self.lst_Steps.setItemWidget(item,lbl_info)
		self.lst_Steps.setCurrentItem(item)
		item.setSizeHint(QSize(lbl_info.lbl_info.width(), lbl_info.sizeHint().height()))
		self.progressBar()
		self.th.setTarget("doUpgrade")
		self.th.start()
		self.th.end.connect(self._endUpgrade)
		self.noreturn=1	
	#def _doLastStepUpgrade

	def _beginLastStepUpgrade(self):
		item = QListWidgetItem(self.lst_Steps)
		lbl_info=QStepLine()
		lbl_info.setText("{0}<br>{1}".format(llxupgrader.i18n("LASTCHANCE"),llxupgrader.i18n("DISMISS")))
		lbl_info.clicked.connect(self._doLastStepUpgrade)
		lbl_info.btn_ko.clicked.connect(self._revertAll)
		self.lst_Steps.addItem(item)
		self.lst_Steps.setItemWidget(item,lbl_info)
		self.lst_Steps.setCurrentItem(item)
		item.setSizeHint(QSize(lbl_info.lbl_info.width(), lbl_info.sizeHint().height()))
	#def _beginLastStepUpgrade

	def _doUpgrade(self):
		item = QListWidgetItem(self.lst_Steps)
		lbl_info=QStepLine()
		lbl_info.setText(llxupgrader.i18n("DISABLEREPOS"))
		lbl_info.btn_ok.setVisible(False)
		lbl_info.btn_ko.setVisible(False)
		self.lst_Steps.addItem(item)
		self.lst_Steps.setItemWidget(item,lbl_info)
		self.lst_Steps.setCurrentItem(item)
		item.setSizeHint(QSize(lbl_info.lbl_info.width(), lbl_info.sizeHint().height()))
		try:
			self.th.setTarget("disablerepos")
			self.th.start()
			self.th.disabled.connect(self._beginLastStepUpgrade)
			self.noreturn=1	
		except Exception as e:
			print(e)
			lbl_info.setText("{}".format(e))
			item.setSizeHint(QSize(lbl_info.lbl_info.width(), lbl_info.sizeHint().height()))
			return(False)
	#def doUpgrade

	def beginUpgrade(self):
		self.chk_sure.setDisabled(True)
		item = QListWidgetItem(self.lst_Steps)
		lbl_info=QStepLine()
		self.lst_Steps.addItem(item)
		self.lst_Steps.setItemWidget(item,lbl_info)
		if llxupgrader.upgradeCurrentState():
			lbl_info.btn_ok.setVisible(False)
			lbl_info.btn_ko.setVisible(False)
			lbl_info.setText((llxupgrader.i18n("PENDING")))
		else:
			lbl_info.setText("<p>{0}</p><p>{1}</p><p><b>{2}</b></p>".format(llxupgrader.i18n("DISABLE"),llxupgrader.i18n("DEFAULT"),llxupgrader.i18n("UNDO")))
			lbl_info.clicked.connect(self._doUpgrade)
		item.setSizeHint(QSize(lbl_info.lbl_info.width(), lbl_info.sizeHint().height()))
		self.lst_Steps.setCurrentItem(item)
	#def beginUpgrade

	def progressBar(self):
		item=self.lst_Steps.item(0)
		wdg=self.lst_Steps.itemWidget(item)
		self.lst_Steps.setCurrentItem(item)
		self.thProgress.prg=wdg
		self.thProgress.start()


	def renderGui(self):
		lay=QGridLayout()
		self.setLayout(lay)
		self.lst_Steps=QListWidget()
		banner=QStepLine()
		banner.enableImg("/usr/share/llx-upgrade-release/rsrc/bkg.png")
		banner.btn_ok.setVisible(False)
		banner.btn_ko.setVisible(False)
		itemb = QListWidgetItem(self.lst_Steps)
		self.lst_Steps.addItem(itemb)
		self.lst_Steps.setItemWidget(itemb,banner)
		lbl_info=QStepLine()
		lbl_info.btn_ok.setEnabled(False)
		lbl_info.clicked.connect(self.beginUpgrade)
		lay.addWidget(self.lst_Steps,0,0,1,2)
		self.chk_sure=QCheckBox(llxupgrader.i18n("DISCLAIMERGUI"))
		self.chk_sure.stateChanged.connect(lambda x:lbl_info.btn_ok.setEnabled(self.chk_sure.isChecked()))
		lay.addWidget(self.chk_sure,3,0,1,2,Qt.AlignLeft)
		if self.upgradeTo:
			lbl_info.setText("<i>{0}: {1}</i><p><b>{3}</b></p>".format(llxupgrader.i18n("AVAILABLE"),self.upgradeTo["Name"].split(":")[1].strip(),llxupgrader.i18n("ASK"),llxupgrader.i18n("DISMISS")))
			item = QListWidgetItem(self.lst_Steps)
			self.lst_Steps.addItem(item)
			self.lst_Steps.setItemWidget(item,lbl_info)
			itemb.setSizeHint(QSize(lbl_info.width(), lbl_info.height()))
			item.setSizeHint(QSize(lbl_info.width(), lbl_info.height()))
		self.resize(QSize(self.lst_Steps.width(),self.lst_Steps.height()))
	#def renderGui

	def chkUpAvailable(self):
		url="https://raw.githubusercontent.com/juanma1980/llx-upgrade-release/master/files/meta-release"
		meta=llxupgrader.downloadFile(url)
		with open(meta,"r") as f:
			metadata=llxupgrader.processMetaRelease(f.readlines())

		upgradeTo=llxupgrader.chkReleaseAvailable(metadata)
		return(upgradeTo)
	#def chkUpAvailable
#class upgraderGui

##### MAIN APP ######

if os.geteuid()!=0:
	cmd=["kdialog","--error",llxupgrader.i18n("ROOT"),"--title","Error"]
	subprocess.run(cmd)
	sys.exit(10)
app=QApplication(["Lliurex Release Upgrade"])
gui=upgraderGui()
gui.renderGui()
gui.show()
app.exec_()

