#!/usr/bin/python3

import llxupgrader

url="https://raw.githubusercontent.com/juanma1980/llx-upgrade-release/master/files/meta-release"
meta=llxupgrader.downloadFile(url)
with open(meta,"r") as f:
	metadata=llxupgrader.processMetaRelease(f.readlines())

upgradeTo=llxupgrader.chkReleaseAvailable(metadata)
if len(upgradeTo)>0:
	print("{0}: {1}".format(llxupgrdeer.i18n("AVAILABLE"),upgradeTo["Name"].split(":")[1].strip()))
	upgrade=input("{}? y/[n]: ".format(llxupgrader.i18n("ASK")))
	if upgrade!="y":
		print(llxupgrader.i18n("ABORT"))
		sys.exit(2)
if llxupgrader.disclaimerAgree()==False:
	print(llxupgrader.i18n("ABORT"))
	sys.exit(2)
print()
print(llxupgrader.i18n("BEGIN"))
if llxupgrader.upgradeCurrentState():
	print(llxupgrader.i18n("PENDING"))
	sys.exit(3)
print(llxupgrader.i18n("DISABLE"))
print(llxupgrader.i18n("DEFAULT"))
print("\n  **** {} **** \n".format(llxupgrader.i18n("UNDO").upper()))
abort=input("[n]/ok: ")
if abort!="ok":
	print(llxupgrader.i18n("ABORT"))
	sys.exit(2)
llxupgrader.disableRepos()
tools=llxupgrader.prepareFiles(upgradeTo)
print(llxupgrader.i18n("EXTRACT"))
llxupgrader.enableUpgradeRepos(tools)
llxupgrader.launchLliurexUpgrade()
llxupgrader.chkUpgradeResult()
sys.exit(0)
